---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-oauth2-proxy
  name: test-oauth2-proxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-oauth2-proxy
  type: LoadBalancer
---
.kind: v1::Service
.M.name: test-oauth2-proxy
ports:
- .port: 80:8080
  protocol: TCP
selector:
  app: test-oauth2-proxy
type: LoadBalancer
